name: Create a comment on a new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubutu-latest
    steps:
      - name: 'dun gitup context'
        run: echo '${{ toJSON(github.event) }} | jq
        shell: bash
